services:
  - type: web
    name: lunarmatch
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/status
    envVars:
      - key: PORT
        value: 8000
      - key: HOST
        value: 0.0.0.0
